### ISSUE TITLE
Something in `dprint` is deleting content

### ISSUE THREAD

**Issue by horo-fox** [g-plane/markup_fmt#30]
Given the fix for #27 was in 0.10.0, I gave `markup_fmt` a try on another project. Unfortunately, *something* in dprint hates a specific comment:

```astro
---
({
    // '
})
---

<p>Blah</p>
```

See dprint playground: https://dprint.dev/playground/#code/LQiwCgAoG8IAgXA9EuByCBfAlBEwIIAeABwD4AhAGwEMALIpcoA/config/N4XyA/plugin/BYFxAcGcC4HpfAGwK4HMCWA7SA6AJuAE5Yj4CmAbrKgLRICGmZsAtvYQNbLgD6AZixA0KABhwBOHGIDu9SCyA (need to switch file extension to `.astro`)

---

This probably isn't because of `markup_fmt`, but that's what lets me use the `.astro` format so...

**Comment by g-plane** [comment]
I found this bug was caused by the un-matched single quote. If you add a single quote (to make it match), it will work.

Though it's a bug, the reason is markup_fmt can't parse JS/TS code in Astro frontmatter, and it can't do too much syntax checking. For example, it doesn't know there's a line comment.
