### ISSUE TITLE
deno fmt should keep line breaks for the html class attribute.

### ISSUE THREAD

**Issue by MohammadSu1** [g-plane/markup_fmt#75]
I use tailwindcss and often end up sometimes with lots of classes in my either .svelte files or .html files.
To make them more readable and compact I structure them with linebreaks. However, currently deno fmt will rearrange them in one long line that needs horizontal scrolling in VScode to review.
```
<div
  class="aclass aclass aclass aclass aclass 
aclass aclass aclass aclass aclass aclass aclass 
aclass aclass aclass aclass aclass aclass aclass 
aclass aclass aclass aclass aclass aclass aclass 
aclass aclass aclass aclass aclass aclass aclass 
aclass aclass aclass aclass aclass aclass"
>
  div with lost of tailwindcss classes
</div>
```
expected:
```
<div
  class="aclass aclass aclass aclass aclass 
    aclass aclass aclass aclass aclass aclass aclass 
    aclass aclass aclass aclass aclass aclass aclass 
    aclass aclass aclass aclass aclass aclass aclass 
    aclass aclass aclass aclass aclass aclass aclass 
    aclass aclass aclass aclass aclass aclass"
>
  div with lost of tailwindcss classes
</div>
```
actual (deno 2.0.4 (stable, release, x86_64-pc-windows-msvc)
```
<div
  class="aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass aclass"
>
  div with lost of tailwindcss classes
</div>
```

Originally reported in https://github.com/denoland/deno/issues/26690

**Comment by g-plane** [comment]
@UnknownPlatypus How do you think? Should we keep classes on the same line or add line breaks? Or, add an option to allow users to control this?

**Comment by UnknownPlatypus** [comment]
@g-plane I feel like if we try to add line break we will never get it right because some users will want:
- one class per line (but this is terrible and was even rollbacked in prettier, see https://github.com/prettier/prettier/issues/10918
- structured group of classes (first line is for margins tailwind classes, second line for colors, etc...)
- everything on a single line (which I believe is still better, even for long classes because I value more being able to quickly identify the overall HTML structure. Bonus point if we avoid breaking for a single attr, which I tried to address in https://github.com/g-plane/markup_fmt/pull/42)

In my opinion, the best and most flexible way to handle this would be to follow adam wishlist he explained with many details here https://github.com/prettier/prettier/issues/10918#issuecomment-971055862

We could have a flag to choose between current behavior (always put everything on one line) and the new behavior (format on one line if there are no pre-existing newlines, otherwise format on multiple lines)

To me it's the best of both worlds

**Comment by g-plane** [comment]
That solution sounds great, at least better than simply choosing adding line breaks or not.
